### ISSUE TITLE
Last.fm sign-in fails when using Firefox 57

### ISSUE THREAD

**Issue by makmm** [agersant/polaris-web#24] opened 2018-11-04 03:41 UTC
read: https://github.com/clementine-player/Clementine/issues/5936

this applies to polaris too

**Comment by agersant** [comment] 2018-11-04 04:05
Thanks for the report!

Closing because this is a dupe of https://github.com/agersant/polaris-web/issues/22.

**Closed by agersant** 2018-11-04 04:05 UTC
